### PR TITLE
Properly handle implicit conversion to integer types.

### PR DESCRIPTION
**Pull request by nsf**
From the commit message:

> Go's reflect API is very picky about arguments to Call method. You can't just
> pass in the "int" when function expects "int64", even on 64 bit machines. This
> patch solves this problem by performing conversions properly. Truncation
> problems however, as well as negative to uint issues are completely ignored.
> Which is perhaps not ideal, but still better than returning "int" when "int32"
> or "int64" is requested.

> I did split the Kind switch cases and moved value -> int and value -> float
> conversions to separate functions. An alternative to that would be using the
> reflection API, which might be less performant. Not that it matters much, but
> this solution is correct, even though looks a bit copy & pasty.

> Oh and of course all "uint" types were completely missing in the function and
> they are now added.

While this commit fixes existing behaviour, i.e. implicit conversions from strings to ints. What worries me is that errors from `strconv.ParseInt(value, 10, 64)` and `strconv.ParseFloat(value, 64)` are returned directly here. I didn't change that behaviour in this patch, but perhaps it would be wise to do so. What do you think, @osteele? Perhaps it would be better to convert those errors into TypeError, so that they are properly caught in `func (e expression) Evaluate(ctx Context)`, instead of causing unnecessary panics?

Anyways, I think I will submit a follow up pull request in a sec if you think it might be a good idea.

### CODE REVIEW

**Comment by nsf** [comment]
Well, I pushed those changes to my master, and they were added to this pull request. Anyways, obviously we can discuss it all. What's okay and what is not. I can rearrange it the way you prefer it to be.

Also some weird results from coverage test.

**Comment by nsf** [comment]
Well, it is done then. I fixed those integer/float conversions in first commit and second commit just converts error values to TypeError, so that when MustConvert throws (panics) them, expression evaluation code won't rethrow it.

Question is what happened with coverage test. Doesn't make sense to me, looks like some glitch.

**Comment by osteele** [comment]
Thanks, I will take a look at code and coverage tonight/tomorrow.

**Comment by nsf** [comment]
ping?

**Comment by nsf** [comment]
Thanks for merging it!

**Pull request merged**
